# circleci manifest yml
version: 2
jobs:
  build:
    docker:
            - image: nats-streaming:latest
    steps:
      - checkout
      - run:
          name: nats-streaming
          command: nat-streaming-server -m 8222
